### ISSUE TITLE
False-alive proxies

### ISSUE THREAD

**Issue by XDMEOW** [Pix4Devs/ProxyEagle#1]
i was just checking 10k proxies and ur tool detected 3k working proxies but in realitty only 152 were alive

**Comment by Z3NTL3** [comment]
I think this problem has arisen because the tool already lists the proxy as valid when it connects. 

I'm looking forward to fixing this problem by also checking if the encoded header has been sent and if so how many bytes will it be, then it is a 100% valid proxy. 

Thanks for mentioning. I will solve it today.

**Comment by Z3NTL3** [comment]
ProxyEagle has now an 2th variant on the source.

Once the proxy server can connect to a website it lists the proxy server as valid instead of determining validity by just connecting and not sending a header for a website connection.

```https://github.com/Pix4Devs/ProxyEagle/blob/main/proxyeagle2.py```
